name: Build Docker images

on:
  push:
    tags:
      - "*"

jobs:
  publish_docker_image:
    name: Build and publish a new docker image to the Github container registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./docker/Dockerfile
          tags: ghcr.io/jirkavrba/kogito-workflows-ui:latest,ghcr.io/jirkavrba/kogito-workflows-ui:${{github.ref_name}}